Import("env")


def source(file):
    return "#/src/prefix_sums/" + file

env["source_files"] += [
    source("prefix_sums.cpp"),
    source("example01.cpp"),
    source("example02.cpp"),
    source("example03.cpp"),
    source("example04.cpp"),
    source("leetcode_problem_303.cpp"),
    source("leetcode_problem_307.cpp"),
    source("example05.cpp"),
    source("example05_kadane_algorithm.cpp"),
    source("example06.cpp"),
    source("example07.cpp"),
    source("example08.cpp")
]
