Import("env")


def source(file):
    return "#/src/" + file

env["source_files"] += [
    source("main.cpp"),
    source("app.cpp")
]


# Prefix Sums
SConscript("#/src/prefix_sums/SConscript", exports="env")